# All makefile fragments assume that $(srcdir) points to the gcc
# directory, not the language subdir
srcdir = /jenhome/jenkins/jobs/LE910Cx_Multi_DAILY/workspace/build/apps_proc/poky/build/tmp-glibc/work-shared/gcc-4.9.3-r0/gcc-4.9.3/gcc
-include ./gcc-interface/Makefile
-include ../gcc-interface/Makefile
