#!/bin/bash

set -e
SERIAL_PORT=/dev/ttyUSB3
OLD_SETTINGS=$(stty -g -F ${SERIAL_PORT})
# Configure the serial port for sending commands
stty -F ${SERIAL_PORT} \
-igncr \
-icrnl \
-ixon \
-ixoff \
-ignbrk \
-brkint \
-imaxbel \
-opost \
-onlcr \
-isig \
-icanon \
-iexten \
-echo \
-echoe \
-echok \
-echoctl \
-echoke \
time 5 \
min 1
# Restore old settings
stty -F ${SERIAL_PORT} "$OLD_SETTINGS"

# Disable local echo
echo 'ATE0' | atinout - ${SERIAL_PORT} -
sleep 0.1
# Hide the output of this command since it is only used here
# to clear the buffer if local echo was enabled prior to ATE0 being sent
echo 'AT' | atinout - ${SERIAL_PORT} - > /dev/null
sleep 0.1
echo 'AT#ENAEVMONI=0' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#ENAEVMONICFG=3,1,2' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="SMSIN",0,1,"TEST"' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="SMSIN",0,0,"AT#GPIO=3,1,1"' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="SMSIN",1' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="GPIO3",0,1,3' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="GPIO3",0,2,1' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="GPIO3",0,3,1' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="GPIO3",0,0,"AT#GPIO=3,1,0"' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#EVMONI="GPIO3",1' | atinout - ${SERIAL_PORT} -
sleep 0.1
echo 'AT#ENAEVMONI=1' | atinout - ${SERIAL_PORT} -
sleep 0.1
# Do not store text messages when received
echo 'AT+CNMI=2,2,0,0,0' | atinout - ${SERIAL_PORT} -
sleep 0.1
# Clear out SMS storage in case spam texts were previously received
echo 'AT+CMGD=1,4' | atinout - ${SERIAL_PORT} -

exit 0
