#!/bin/bash

set -e

FILE_PATH="/usr/lib/telit-firmware/m2mapz.bin"
SERIAL_PORT="/dev/ttyUSB3"
OLD_SETTINGS=$(stty -g -F ${SERIAL_PORT})

stty -F ${SERIAL_PORT} \
-ixon \
-ixoff \
-ignbrk \
-brkint \
-imaxbel \
-opost \
-onlcr \
-isig \
-icanon \
-iexten \
-echo \
-echoe \
-echok \
-echoctl \
-echoke \
time 5 \
min 1

try_at_command()
{
    local at_cmd="$1"
    local max_retries=5
    for ((i=1; i<=max_retries; i++)); do
        echo $at_cmd
        output=$(echo "$at_cmd" | atinout - "$SERIAL_PORT" - 2>&1)
        status=$?
        if [[ $status -eq 0 && "$output" == *"OK"* ]]; then
            echo $output
            return 0
        fi
    done
}

upload_firmware_file()
{
    local file_size_bytes=$(stat -c %s "$FILE_PATH")
    echo 'AT#M2MWRITE="m2mapz.bin",'${file_size_bytes}',1' | atinout - "$SERIAL_PORT" - &
    # Need to use a sleep here because atinout cannot handle the firmware upload command
    sleep 1
    cat ${FILE_PATH} > ${SERIAL_PORT}
}

# disable local echo
try_at_command "ATE0"

upload_firmware_file
# Start firmware file immediately
try_at_command 'AT#M2MRUN=1,"m2mapz.bin"'
try_at_command 'AT#M2MRUN=5,"m2mapz.bin"'

# Restore old settings
stty -F ${SERIAL_PORT} "$OLD_SETTINGS"

exit 0
